services:
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak
    command: start-dev
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_DB=postgres
      - KC_DB_URL_HOST=keycloak-db
      - KC_DB_URL_DATABASE=keycloakDatabase
      - KC_DB_USERNAME=keycloak
      - KC_DB_PASSWORD=password123
    networks:
      - auth-network
      - keycloak-database
    ports:
      - "8080:8080"
    volumes:
      - keycloak-data-volume:/var/lib/keycloak/data
  
  authorizationservice:
    image: authorizationservice
    build:
      context: .
      dockerfile: AuthorizationService/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
    networks:
      - auth-network
    ports:
      - "5001:5001"
  
  
  keycloak-db:
    image: postgres:15
    environment:
      POSTGRES_DB: keycloakDatabase
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password123
    networks:
      - keycloak-database
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
  keycloak-data-volume:

networks:
  auth-network:
  keycloak-database: