services:
  
  rabbitmq:
    image: rabbitmq:3-management
    container_name: RabbitMQ
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 20s
      timeout: 10s
      retries: 3
    restart: always
    networks:
      - backend
    ports:
      - "5672:5672"         
      - "15672:15672"      
  
  api-gateway:
    image: api-gateway
    build:
      context: .
      dockerfile: ApiGateway/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
    networks:
      - backend
    ports:
      - "5000:5000"
      
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak
    command: start-dev
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_DB=postgres
      - KC_DB_URL_HOST=keycloak-db
      - KC_DB_URL_DATABASE=keycloakDatabase
      - KC_DB_USERNAME=keycloak
      - KC_DB_PASSWORD=password123
    networks:
      - backend
      - keycloak-database
    ports:
      - "8080:8080"
    volumes:
      - keycloak-data-volume:/var/lib/keycloak/data
  
  authorization-service:
    image: authorization-service
    build:
      context: .
      dockerfile: AuthorizationService/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
    networks:
      - backend
    ports:
      - "5001:5001"
        
  order-service:
    image: order-service
    build:
      context: .
      dockerfile: OrderService/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
    networks:
      - backend
      - order-database
      - event-network
    ports:
      - "5002:5002"
  
  product-service:
    image: product-service
    build:
      context: .
      dockerfile: ProductService/Dockerfile  
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
    networks:
      - backend
      - product-database
    ports:
      - "5003:5003"
  
  keycloak-db:
    image: postgres:15
    environment:
      POSTGRES_DB: keycloakDatabase
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password123
    networks:
      - keycloak-database
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  
  product-db:
    image: postgres:15
    environment:
      POSTGRES_DB: productDatabase
      POSTGRES_USER: product
      POSTGRES_PASSWORD: password123
    networks:
      - product-database
    ports:
      - "5433:5432"
    volumes:
      - pgdata1:/var/lib/postgresql/data
  
  order-db:
    image: postgres:15
    environment:
      POSTGRES_DB: orderDatabase
      POSTGRES_USER: order
      POSTGRES_PASSWORD: password123
    networks:
      - order-database
    ports:
      - "5434:5432"
    volumes:
      - pgdata2:/var/lib/postgresql/data
    
  eventstore:
    image: eventstore/eventstore:latest
    container_name: eventstore
    restart: always
    environment:
      - EVENTSTORE_CLUSTER_SIZE=1
      - EVENTSTORE_RUN_PROJECTIONS=All
      - EVENTSTORE_START_STANDARD_PROJECTIONS=true
      - EVENTSTORE_HTTP_PORT=2113
      - EVENTSTORE_INSECURE=true
    networks:
      - event-network
    ports:
      - "2113:2113" # HTTP API
    volumes:
      - eventstore-data:/var/lib/eventstore


volumes:
  pgdata:
  pgdata1:
  pgdata2:
  keycloak-data-volume:
  eventstore-data:
    

networks:
  backend:
  auth-network:
  keycloak-database:  
  product-database:
  order-database:
  event-network:
    driver: bridge
  





  

  
