# This is a generated file. Not intended for manual editing.
services:
  authorizationservice:
    build:
      context: "C:\\Users\\kaxaq\\RiderProjects\\ E-Commerce-Api-with-.NET-8.0"
      dockerfile: "AuthorizationService/Dockerfile"
      target: "base"
    command: []
    entrypoint:
    - "dotnet"
    - "/app/bin/Debug/net8.0/AuthorizationService.dll"
    environment:
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
    image: "authorizationservice:dev"
    ports: []
    volumes:
    - "C:\\Users\\kaxaq\\RiderProjects\\ E-Commerce-Api-with-.NET-8.0\\AuthorizationService:/app:rw"
    - "C:\\Users\\kaxaq\\RiderProjects\\ E-Commerce-Api-with-.NET-8.0:/src:rw"
    - "C:\\Users\\kaxaq\\.nuget\\packages:/home/app/.nuget/packages"
    working_dir: "/app"
